// Central SVG icon library — inline components, no emoji dependency
// Each component renders a 24x24 viewBox SVG, styled via class prop

export { default as IconCheck }         from './IconCheck.vue'
export { default as IconX }             from './IconX.vue'
export { default as IconShield }        from './IconShield.vue'
export { default as IconBan }           from './IconBan.vue'
export { default as IconWarning }       from './IconWarning.vue'
export { default as IconBrain }         from './IconBrain.vue'
export { default as IconMap }           from './IconMap.vue'
export { default as IconCurrency }      from './IconCurrency.vue'
export { default as IconCar }           from './IconCar.vue'
export { default as IconChart }         from './IconChart.vue'
export { default as IconStar }          from './IconStar.vue'
export { default as IconClock }         from './IconClock.vue'
export { default as IconPlay }          from './IconPlay.vue'
export { default as IconTrash }         from './IconTrash.vue'
export { default as IconSave }          from './IconSave.vue'
export { default as IconPlus }          from './IconPlus.vue'
export { default as IconSearch }        from './IconSearch.vue'
export { default as IconTag }           from './IconTag.vue'
export { default as IconDatabase }      from './IconDatabase.vue'
export { default as IconFilter }        from './IconFilter.vue'
export { default as IconChevronDown }   from './IconChevronDown.vue'
export { default as IconChevronUp }     from './IconChevronUp.vue'
export { default as IconArrowRight }    from './IconArrowRight.vue'
export { default as IconLock }          from './IconLock.vue'
export { default as IconUser }          from './IconUser.vue'
export { default as IconBookOpen }      from './IconBookOpen.vue'
export { default as IconBolt }          from './IconBolt.vue'
